/**
 * اطلاعات کامل استان‌ها و شهرهای ایران
 * شامل ۳۱ استان با تمام شهرها و مختصات
 */

export interface City {
  name: string;
  slug: string;
}

export interface Province {
  id: number;
  name: string;
  slug: string;
  cities: City[];
}

export const IRAN_PROVINCES: Province[] = [
  {
    id: 1, name: "آذربایجان شرقی", slug: "azarbaijan-sharghi",
    cities: [
      { name: "تبریز", slug: "tabriz" },
      { name: "مراغه", slug: "maragheh" },
      { name: "مرند", slug: "marand" },
      { name: "اهر", slug: "ahar" },
      { name: "میانه", slug: "mianeh" },
      { name: "بناب", slug: "bonab" },
      { name: "سراب", slug: "sarab" },
      { name: "آذرشهر", slug: "azarshahr" },
      { name: "هشترود", slug: "hashtrud" },
      { name: "ملکان", slug: "malekan" },
      { name: "بستان‌آباد", slug: "bostanabad" },
      { name: "اسکو", slug: "osku" },
      { name: "عجب‌شیر", slug: "ajabshir" },
      { name: "شبستر", slug: "shabestar" },
      { name: "خوی", slug: "khoy" },
      { name: "سلماس", slug: "salmas" },
      { name: "ماکو", slug: "maku" },
      { name: "چالدران", slug: "chaldoran" },
      { name: "پلدشت", slug: "poldasht" },
      { name: "جلفا", slug: "jolfa" },
      { name: "ورزقان", slug: "varzeqan" },
      { name: "تیکمه‌داش", slug: "tikmehdash" },
      { name: "هریس", slug: "haris" },
      { name: "ایلخچی", slug: "ilkhchi" },
      { name: "خسروشاه", slug: "khosrowshahr" },
    ],
  },
  {
    id: 2, name: "آذربایجان غربی", slug: "azarbaijan-gharbi",
    cities: [
      { name: "ارومیه", slug: "urmia" },
      { name: "خوی", slug: "khoy" },
      { name: "بوکان", slug: "bukan" },
      { name: "مهاباد", slug: "mahabad" },
      { name: "میاندوآب", slug: "miandoab" },
      { name: "نقده", slug: "naqadeh" },
      { name: "پیرانشهر", slug: "piranshahr" },
      { name: "سردشت", slug: "sardasht" },
      { name: "اشنویه", slug: "oshnavieh" },
      { name: "شاهین‌دژ", slug: "shahindezh" },
      { name: "تکاب", slug: "takab" },
      { name: "سلماس", slug: "salmas" },
      { name: "ماکو", slug: "maku" },
      { name: "چایپاره", slug: "chaypareh" },
      { name: "شوط", slug: "showt" },
      { name: "پلدشت", slug: "poldasht" },
      { name: "چالدران", slug: "chaldoran" },
    ],
  },
  {
    id: 3, name: "اردبیل", slug: "ardabil",
    cities: [
      { name: "اردبیل", slug: "ardabil" },
      { name: "پارس‌آباد", slug: "parsabad" },
      { name: "مشگین‌شهر", slug: "meshgin-shahr" },
      { name: "خلخال", slug: "khalkhal" },
      { name: "گرمی", slug: "germi" },
      { name: "نمین", slug: "namin" },
      { name: "نیر", slug: "nir" },
      { name: "سرعین", slug: "sareyn" },
      { name: "بیله‌سوار", slug: "bileh-savar" },
      { name: "کوثر", slug: "kowsar" },
      { name: "اصلاندوز", slug: "aslanduz" },
    ],
  },
  {
    id: 4, name: "اصفهان", slug: "isfahan",
    cities: [
      { name: "اصفهان", slug: "isfahan" },
      { name: "کاشان", slug: "kashan" },
      { name: "خمینی‌شهر", slug: "khomeyni-shahr" },
      { name: "نجف‌آباد", slug: "najafabad" },
      { name: "شاهین‌شهر", slug: "shahin-shahr" },
      { name: "شهرضا", slug: "shahreza" },
      { name: "فلاورجان", slug: "falavarjan" },
      { name: "مبارکه", slug: "mobarakeh" },
      { name: "لنجان", slug: "lenjan" },
      { name: "برخوار", slug: "borkhar" },
      { name: "آران و بیدگل", slug: "aran-bidgol" },
      { name: "گلپایگان", slug: "golpayegan" },
      { name: "سمیرم", slug: "semirom" },
      { name: "نائین", slug: "nain" },
      { name: "خور و بیابانک", slug: "khor-biyabank" },
      { name: "نطنز", slug: "natanz" },
      { name: "فریدن", slug: "fereydan" },
      { name: "فریدون‌شهر", slug: "fereydun-shahr" },
      { name: "دهاقان", slug: "dehaqan" },
      { name: "چادگان", slug: "chadegan" },
      { name: "تیران و کرون", slug: "tiran-karvan" },
      { name: "بوئین و میاندشت", slug: "buin-miandasht" },
    ],
  },
  {
    id: 5, name: "البرز", slug: "alborz",
    cities: [
      { name: "کرج", slug: "karaj" },
      { name: "فردیس", slug: "fardis" },
      { name: "هشتگرد", slug: "hashtgerd" },
      { name: "نظرآباد", slug: "nazarabad" },
      { name: "طالقان", slug: "taleqan" },
      { name: "ساوجبلاغ", slug: "savojbolagh" },
      { name: "اشتهارد", slug: "eshtehard" },
      { name: "محمدشهر", slug: "mohammad-shahr" },
      { name: "ماهدشت", slug: "mahdasht" },
      { name: "کمال‌شهر", slug: "kamal-shahr" },
      { name: "گرمدره", slug: "garmdareh" },
    ],
  },
  {
    id: 6, name: "ایلام", slug: "ilam",
    cities: [
      { name: "ایلام", slug: "ilam" },
      { name: "ایوان", slug: "eyvan" },
      { name: "دهلران", slug: "dehloran" },
      { name: "آبدانان", slug: "abdanan" },
      { name: "دره‌شهر", slug: "dareh-shahr" },
      { name: "ملک‌شاهی", slug: "malekshahi" },
      { name: "چرداول", slug: "chardavol" },
      { name: "مهران", slug: "mehran" },
      { name: "بدره", slug: "badreh" },
      { name: "سیروان", slug: "sirvan" },
    ],
  },
  {
    id: 7, name: "بوشهر", slug: "bushehr",
    cities: [
      { name: "بوشهر", slug: "bushehr" },
      { name: "برازجان", slug: "borazjan" },
      { name: "بندر گناوه", slug: "bandar-ganaveh" },
      { name: "بندر دیلم", slug: "bandar-deylam" },
      { name: "خارک", slug: "khark" },
      { name: "تنگستان", slug: "tangestan" },
      { name: "دشتستان", slug: "dashtestan" },
      { name: "دشتی", slug: "dashti" },
      { name: "جم", slug: "jam" },
      { name: "کنگان", slug: "kangan" },
      { name: "عسلویه", slug: "asaluyeh" },
      { name: "دیر", slug: "dayyer" },
    ],
  },
  {
    id: 8, name: "تهران", slug: "tehran",
    cities: [
      { name: "تهران", slug: "tehran" },
      { name: "شهریار", slug: "shahriar" },
      { name: "اسلامشهر", slug: "eslamshahr" },
      { name: "رباط‌کریم", slug: "robat-karim" },
      { name: "ورامین", slug: "varamin" },
      { name: "پاکدشت", slug: "pakdasht" },
      { name: "دماوند", slug: "damavand" },
      { name: "شمیرانات", slug: "shemiranat" },
      { name: "فیروزکوه", slug: "firuzkuh" },
      { name: "قدس", slug: "qods" },
      { name: "ملارد", slug: "malard" },
      { name: "پیشوا", slug: "pishva" },
      { name: "بهارستان", slug: "baharestan" },
      { name: "قرچک", slug: "qarchak" },
      { name: "پردیس", slug: "pardis" },
      { name: "اندیشه", slug: "andisheh" },
      { name: "باقرشهر", slug: "bagher-shahr" },
      { name: "صبا‌شهر", slug: "saba-shahr" },
    ],
  },
  {
    id: 9, name: "چهارمحال و بختیاری", slug: "chaharmahal-bakhtiari",
    cities: [
      { name: "شهرکرد", slug: "shahrekord" },
      { name: "بروجن", slug: "borujen" },
      { name: "لردگان", slug: "lordegan" },
      { name: "فارسان", slug: "farsan" },
      { name: "کیار", slug: "kiar" },
      { name: "کوهرنگ", slug: "kohrang" },
      { name: "اردل", slug: "ardal" },
      { name: "سامان", slug: "saman" },
      { name: "بن", slug: "ben" },
    ],
  },
  {
    id: 10, name: "خراسان جنوبی", slug: "khorasan-jonubi",
    cities: [
      { name: "بیرجند", slug: "birjand" },
      { name: "قائن", slug: "ghaen" },
      { name: "فردوس", slug: "ferdows" },
      { name: "طبس", slug: "tabas" },
      { name: "نهبندان", slug: "nehbandan" },
      { name: "سربیشه", slug: "sarbisheh" },
      { name: "درمیان", slug: "darmian" },
      { name: "خوسف", slug: "khusf" },
      { name: "زیرکوه", slug: "zirkuh" },
    ],
  },
  {
    id: 11, name: "خراسان رضوی", slug: "khorasan-razavi",
    cities: [
      { name: "مشهد", slug: "mashhad" },
      { name: "نیشابور", slug: "neyshabur" },
      { name: "سبزوار", slug: "sabzevar" },
      { name: "قوچان", slug: "quchan" },
      { name: "تربت حیدریه", slug: "torbat-heydarieh" },
      { name: "کاشمر", slug: "kashmar" },
      { name: "تربت جام", slug: "torbat-jam" },
      { name: "چناران", slug: "chenaran" },
      { name: "درگز", slug: "dargaz" },
      { name: "فریمان", slug: "fariman" },
      { name: "گناباد", slug: "gonabad" },
      { name: "بردسکن", slug: "bardaskan" },
      { name: "خواف", slug: "khaf" },
      { name: "رشتخوار", slug: "rashtkhar" },
      { name: "سرخس", slug: "sarakhs" },
      { name: "بجستان", slug: "bajestan" },
      { name: "بینالود", slug: "binalud" },
      { name: "کلات", slug: "kalat" },
      { name: "خلیل‌آباد", slug: "khalilabad" },
      { name: "زاوه", slug: "zaveh" },
      { name: "مه‌ولات", slug: "mahvelat" },
      { name: "صالح‌آباد", slug: "salehabad" },
      { name: "فیروزه", slug: "firouzeh" },
      { name: "باخرز", slug: "bakharz" },
      { name: "طرقبه-شاندیز", slug: "torqabeh-shandiz" },
    ],
  },
  {
    id: 12, name: "خراسان شمالی", slug: "khorasan-shomali",
    cities: [
      { name: "بجنورد", slug: "bojnurd" },
      { name: "اسفراین", slug: "esfarayen" },
      { name: "شیروان", slug: "shirvan" },
      { name: "جاجرم", slug: "jajarm" },
      { name: "مانه و سملقان", slug: "maneh-samalqan" },
      { name: "فاروج", slug: "faruj" },
      { name: "گرمه", slug: "garmeh" },
      { name: "راز و جرگلان", slug: "raz-jargalan" },
      { name: "موان", slug: "movan" },
    ],
  },
  {
    id: 13, name: "خوزستان", slug: "khuzestan",
    cities: [
      { name: "اهواز", slug: "ahvaz" },
      { name: "آبادان", slug: "abadan" },
      { name: "خرمشهر", slug: "khorramshahr" },
      { name: "دزفول", slug: "dezful" },
      { name: "مسجدسلیمان", slug: "masjed-solyman" },
      { name: "ایذه", slug: "izeh" },
      { name: "شوشتر", slug: "shushtar" },
      { name: "بهبهان", slug: "behbahan" },
      { name: "ماهشهر", slug: "mahshahr" },
      { name: "شوش", slug: "shush" },
      { name: "امیدیه", slug: "omidieh" },
      { name: "اندیمشک", slug: "andimeshk" },
      { name: "رامهرمز", slug: "ramhormoz" },
      { name: "هندیجان", slug: "hendijan" },
      { name: "لالی", slug: "lali" },
      { name: "شادگان", slug: "shadegan" },
      { name: "گتوند", slug: "gotvand" },
      { name: "هویزه", slug: "hoveyzeh" },
      { name: "باوی", slug: "bavi" },
      { name: "حمیدیه", slug: "hamidieh" },
      { name: "بندر امام خمینی", slug: "bandar-imam" },
      { name: "آغاجاری", slug: "aghajari" },
      { name: "کارون", slug: "karun" },
      { name: "کرخه", slug: "karkheh" },
    ],
  },
  {
    id: 14, name: "زنجان", slug: "zanjan",
    cities: [
      { name: "زنجان", slug: "zanjan" },
      { name: "ابهر", slug: "abhar" },
      { name: "خدابنده", slug: "khodabandeh" },
      { name: "خرمدره", slug: "khorramdareh" },
      { name: "ایجرود", slug: "ijrud" },
      { name: "طارم", slug: "tarom" },
      { name: "ماهنشان", slug: "mahneshan" },
      { name: "سلطانیه", slug: "soltanieh" },
    ],
  },
  {
    id: 15, name: "سمنان", slug: "semnan",
    cities: [
      { name: "سمنان", slug: "semnan" },
      { name: "شاهرود", slug: "shahroud" },
      { name: "دامغان", slug: "damghan" },
      { name: "گرمسار", slug: "garmsar" },
      { name: "مهدی‌شهر", slug: "mahdi-shahr" },
      { name: "میامی", slug: "mayamey" },
      { name: "آرادان", slug: "aradan" },
      { name: "سرخه", slug: "sorkheh" },
      { name: "بسطام", slug: "bastam" },
    ],
  },
  {
    id: 16, name: "سیستان و بلوچستان", slug: "sistan-baluchestan",
    cities: [
      { name: "زاهدان", slug: "zahedan" },
      { name: "چابهار", slug: "chabahar" },
      { name: "زابل", slug: "zabol" },
      { name: "ایرانشهر", slug: "iranshahr" },
      { name: "سراوان", slug: "saravan" },
      { name: "خاش", slug: "khas" },
      { name: "کنارک", slug: "konarak" },
      { name: "نیک‌شهر", slug: "nik-shahr" },
      { name: "مهرستان", slug: "mehrestan" },
      { name: "سرباز", slug: "sarbaz" },
      { name: "فنوج", slug: "fanuj" },
      { name: "دلگان", slug: "dalgan" },
      { name: "هامون", slug: "hamun" },
      { name: "نیمروز", slug: "nimruz" },
      { name: "میرجاوه", slug: "mirjaveh" },
      { name: "تیس", slug: "tis" },
      { name: "قصرقند", slug: "ghasr-e-qand" },
    ],
  },
  {
    id: 17, name: "فارس", slug: "fars",
    cities: [
      { name: "شیراز", slug: "shiraz" },
      { name: "مرودشت", slug: "marvdasht" },
      { name: "جهرم", slug: "jahrom" },
      { name: "فیروزآباد", slug: "firuzabad" },
      { name: "کازرون", slug: "kazerun" },
      { name: "لارستان", slug: "larestan" },
      { name: "فسا", slug: "fasa" },
      { name: "داراب", slug: "darab" },
      { name: "اقلید", slug: "eqlid" },
      { name: "نی‌ریز", slug: "neyriz" },
      { name: "سپیدان", slug: "sepidan" },
      { name: "ممسنی", slug: "mamasani" },
      { name: "پاسارگاد", slug: "pasargad" },
      { name: "بوانات", slug: "bavanat" },
      { name: "سروستان", slug: "sarvestan" },
      { name: "خرامه", slug: "kharameh" },
      { name: "قیر و کارزین", slug: "ghir-karzin" },
      { name: "زرقان", slug: "zarqan" },
      { name: "کوار", slug: "kavar" },
      { name: "استهبان", slug: "estahban" },
      { name: "خنج", slug: "khonj" },
      { name: "لامرد", slug: "lamerd" },
      { name: "فراشبند", slug: "farashband" },
      { name: "ارسنجان", slug: "arsenjan" },
      { name: "رستم", slug: "rostam" },
      { name: "بیضا", slug: "beyza" },
      { name: "خرامه", slug: "kharameh" },
    ],
  },
  {
    id: 18, name: "قزوین", slug: "qazvin",
    cities: [
      { name: "قزوین", slug: "qazvin" },
      { name: "البرز", slug: "alborz" },
      { name: "تاکستان", slug: "takestan" },
      { name: "بوئین‌زهرا", slug: "buin-zahra" },
      { name: "آبیک", slug: "abik" },
      { name: "آوج", slug: "avaj" },
    ],
  },
  {
    id: 19, name: "قم", slug: "qom",
    cities: [
      { name: "قم", slug: "qom" },
      { name: "جعفریه", slug: "jafarieh" },
      { name: "قنوات", slug: "qanavat" },
      { name: "کهک", slug: "kahak" },
      { name: "سلفچگان", slug: "salafchegan" },
    ],
  },
  {
    id: 20, name: "کردستان", slug: "kurdistan",
    cities: [
      { name: "سنندج", slug: "sanandaj" },
      { name: "سقز", slug: "saqqez" },
      { name: "مریوان", slug: "maryvan" },
      { name: "بانه", slug: "baneh" },
      { name: "قروه", slug: "qorveh" },
      { name: "بیجار", slug: "bijar" },
      { name: "دیواندره", slug: "divandarreh" },
      { name: "کامیاران", slug: "kamiaran" },
      { name: "دهگلان", slug: "dehgolan" },
      { name: "سروآباد", slug: "sarvabad" },
    ],
  },
  {
    id: 21, name: "کرمان", slug: "kerman",
    cities: [
      { name: "کرمان", slug: "kerman" },
      { name: "رفسنجان", slug: "rafsanjan" },
      { name: "سیرجان", slug: "sirjan" },
      { name: "زرند", slug: "zarand" },
      { name: "بم", slug: "bam" },
      { name: "جیرفت", slug: "jiroft" },
      { name: "بافت", slug: "baft" },
      { name: "شهربابک", slug: "shahr-e-babak" },
      { name: "کهنوج", slug: "kahnuj" },
      { name: "انار", slug: "anar" },
      { name: "راور", slug: "ravar" },
      { name: "منوجان", slug: "manujan" },
      { name: "رودبار جنوب", slug: "rudbar-jonub" },
      { name: "قلعه‌گنج", slug: "ghaleh-ganj" },
      { name: "نرماشیر", slug: "narmashir" },
      { name: "فهرج", slug: "fahraj" },
      { name: "ریگان", slug: "rigan" },
      { name: "کوهبنان", slug: "kuhbanan" },
      { name: "عنبرآباد", slug: "anbarabad" },
      { name: "ارزوئیه", slug: "orzuiyeh" },
      { name: "فاریاب", slug: "faryab" },
    ],
  },
  {
    id: 22, name: "کرمانشاه", slug: "kermanshah",
    cities: [
      { name: "کرمانشاه", slug: "kermanshah" },
      { name: "اسلام‌آباد غرب", slug: "eslamabad-gharb" },
      { name: "کنگاور", slug: "kangavar" },
      { name: "هرسین", slug: "harsin" },
      { name: "سنقر", slug: "sonqor" },
      { name: "قصر شیرین", slug: "qasr-e-shirin" },
      { name: "سرپل ذهاب", slug: "sarpol-e-zahab" },
      { name: "صحنه", slug: "sahneh" },
      { name: "پاوه", slug: "paveh" },
      { name: "جوانرود", slug: "javanrud" },
      { name: "ثلاث باباجانی", slug: "salas-babajani" },
      { name: "دالاهو", slug: "dalahu" },
      { name: "روانسر", slug: "ravansar" },
      { name: "گیلانغرب", slug: "gilan-gharb" },
    ],
  },
  {
    id: 23, name: "کهگیلویه و بویراحمد", slug: "kohgiluyeh-boyer-ahmad",
    cities: [
      { name: "یاسوج", slug: "yasuj" },
      { name: "دهدشت", slug: "dehdasht" },
      { name: "گچساران", slug: "gachsaran" },
      { name: "سی‌سخت", slug: "sisakht" },
      { name: "لیکک", slug: "likak" },
      { name: "چرام", slug: "charam" },
      { name: "لنده", slug: "landeh" },
      { name: "بهمئی", slug: "bahmai" },
      { name: "باشت", slug: "basht" },
      { name: "مارگون", slug: "margun" },
    ],
  },
  {
    id: 24, name: "گلستان", slug: "golestan",
    cities: [
      { name: "گرگان", slug: "gorgan" },
      { name: "گنبد کاووس", slug: "gonbad-kavus" },
      { name: "علی‌آباد", slug: "aliabad" },
      { name: "بندر ترکمن", slug: "bandar-torkaman" },
      { name: "آزادشهر", slug: "azadshahr" },
      { name: "مینودشت", slug: "minudasht" },
      { name: "کردکوی", slug: "kordkuy" },
      { name: "کلبه", slug: "kalaleh" },
      { name: "آق‌قلا", slug: "aq-qala" },
      { name: "رامیان", slug: "ramian" },
      { name: "مراوه‌تپه", slug: "maraveh-tappeh" },
      { name: "گمیشان", slug: "gomishan" },
      { name: "گالیکش", slug: "galikesh" },
    ],
  },
  {
    id: 25, name: "گیلان", slug: "gilan",
    cities: [
      { name: "رشت", slug: "rasht" },
      { name: "بندر انزلی", slug: "bandar-anzali" },
      { name: "لاهیجان", slug: "lahijan" },
      { name: "رودسر", slug: "rudsar" },
      { name: "صومعه‌سرا", slug: "someh-sara" },
      { name: "آستارا", slug: "astara" },
      { name: "تالش", slug: "talesh" },
      { name: "فومن", slug: "fuman" },
      { name: "شفت", slug: "shaft" },
      { name: "املش", slug: "amlash" },
      { name: "سیاهکل", slug: "siahkal" },
      { name: "آستانه اشرفیه", slug: "astaneh-ashrafieh" },
      { name: "لنگرود", slug: "langarud" },
      { name: "رضوانشهر", slug: "rezvanshahr" },
      { name: "رودبار", slug: "rudbar" },
      { name: "ماسال", slug: "masal" },
    ],
  },
  {
    id: 26, name: "لرستان", slug: "lorestan",
    cities: [
      { name: "خرم‌آباد", slug: "khorramabad" },
      { name: "بروجرد", slug: "borujerd" },
      { name: "دورود", slug: "dorud" },
      { name: "الیگودرز", slug: "aligudarz" },
      { name: "کوهدشت", slug: "kuhdasht" },
      { name: "ازنا", slug: "azna" },
      { name: "پلدختر", slug: "poldokhtar" },
      { name: "نورآباد", slug: "nurabad" },
      { name: "سلسله", slug: "selseleh" },
      { name: "چگنی", slug: "chegeni" },
      { name: "دلفان", slug: "delfan" },
      { name: "رومشکان", slug: "rumeshkan" },
    ],
  },
  {
    id: 27, name: "مازندران", slug: "mazandaran",
    cities: [
      { name: "ساری", slug: "sari" },
      { name: "بابل", slug: "babol" },
      { name: "آمل", slug: "amol" },
      { name: "قائم‌شهر", slug: "qaem-shahr" },
      { name: "چالوس", slug: "chalus" },
      { name: "نوشهر", slug: "nowshahr" },
      { name: "بابلسر", slug: "babolsar" },
      { name: "تنکابن", slug: "tonekabon" },
      { name: "رامسر", slug: "ramsar" },
      { name: "نور", slug: "nur" },
      { name: "محمودآباد", slug: "mahmudabad" },
      { name: "نکا", slug: "neka" },
      { name: "جویبار", slug: "joybar" },
      { name: "بهشهر", slug: "behshahr" },
      { name: "سوادکوه", slug: "savadkuh" },
      { name: "کلاردشت", slug: "kelardasht" },
      { name: "فریدونکنار", slug: "fereydunkenar" },
      { name: "عباس‌آباد", slug: "abbasabad" },
      { name: "سیمرغ", slug: "simorgh" },
      { name: "گلوگاه", slug: "galugah" },
    ],
  },
  {
    id: 28, name: "مرکزی", slug: "markazi",
    cities: [
      { name: "اراک", slug: "arak" },
      { name: "ساوه", slug: "saveh" },
      { name: "خمین", slug: "khomein" },
      { name: "محلات", slug: "mahallat" },
      { name: "دلیجان", slug: "delijan" },
      { name: "شازند", slug: "shazand" },
      { name: "تفرش", slug: "tafresh" },
      { name: "زرندیه", slug: "zarandieh" },
      { name: "فراهان", slug: "farahan" },
      { name: "کمیجان", slug: "komijan" },
      { name: "خنداب", slug: "khandab" },
    ],
  },
  {
    id: 29, name: "هرمزگان", slug: "hormozgan",
    cities: [
      { name: "بندرعباس", slug: "bandar-abbas" },
      { name: "میناب", slug: "minab" },
      { name: "قشم", slug: "qeshm" },
      { name: "کیش", slug: "kish" },
      { name: "بندر لنگه", slug: "bandar-lengeh" },
      { name: "جاسک", slug: "jask" },
      { name: "حاجی‌آباد", slug: "hajiabad" },
      { name: "رودان", slug: "rudan" },
      { name: "خمیر", slug: "khamir" },
      { name: "بستک", slug: "bastak" },
      { name: "بشاگرد", slug: "bashagard" },
      { name: "پارسیان", slug: "parsian" },
      { name: "ابوموسی", slug: "abu-musa" },
      { name: "سیریک", slug: "sirik" },
      { name: "بندر خمیر", slug: "bandar-khamir" },
    ],
  },
  {
    id: 30, name: "همدان", slug: "hamadan",
    cities: [
      { name: "همدان", slug: "hamadan" },
      { name: "ملایر", slug: "malayer" },
      { name: "نهاوند", slug: "nahavand" },
      { name: "اسدآباد", slug: "asadabad" },
      { name: "تویسرکان", slug: "tuyserkan" },
      { name: "بهار", slug: "bahar" },
      { name: "رزن", slug: "razan" },
      { name: "کبودرآهنگ", slug: "kabudarahang" },
      { name: "فامنین", slug: "famenin" },
      { name: "درگزین", slug: "dargazin" },
    ],
  },
  {
    id: 31, name: "یزد", slug: "yazd",
    cities: [
      { name: "یزد", slug: "yazd" },
      { name: "میبد", slug: "meybod" },
      { name: "اردکان", slug: "ardakan" },
      { name: "بافق", slug: "bafq" },
      { name: "مهریز", slug: "mehriz" },
      { name: "تفت", slug: "taft" },
      { name: "اشکذر", slug: "ashkezar" },
      { name: "خاتم", slug: "khatam" },
      { name: "صدوق", slug: "saduq" },
      { name: "بهاباد", slug: "bahabad" },
      { name: "ابرکوه", slug: "abarkuh" },
      { name: "زارچ", slug: "zarach" },
      { name: "مروست", slug: "marvast" },
    ],
  },
];

/** گرفتن لیست استان‌ها برای نمایش در سلکت */
export function getProvinceOptions() {
  return IRAN_PROVINCES.map(p => ({ value: p.name, label: p.name }));
}

/** گرفتن شهرهای یک استان */
export function getCitiesByProvince(provinceName: string): City[] {
  const province = IRAN_PROVINCES.find(p => p.name === provinceName);
  return province?.cities || [];
}

/** گرفتن نام استان از روی slug */
export function getProvinceBySlug(slug: string): Province | undefined {
  return IRAN_PROVINCES.find(p => p.slug === slug);
}
